/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boletin24;

/**
 *
 * @author ped90
 */
public class Ventana1 extends javax.swing.JPanel {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAcept = new javax.swing.JButton();
        Botoncancel = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        Confirm = new javax.swing.JPasswordField();
        Loginshell = new javax.swing.JComboBox<>();
        Homedirectory = new javax.swing.JTextField();
        Group = new javax.swing.JComboBox<>();
        UserID = new javax.swing.JTextField();
        Fullname = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Nombreusuario = new javax.swing.JLabel();
        Nombrecompleto = new javax.swing.JLabel();
        Idusuario = new javax.swing.JLabel();
        Grupo1 = new javax.swing.JLabel();
        Directorio = new javax.swing.JLabel();
        Logear = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        Confirmarcontraseña = new javax.swing.JLabel();
        Mensajetxt = new javax.swing.JLabel();

        BotonAcept.setText("OK");

        Botoncancel.setText("Cancel");

        Password.setText("jPasswordField1");
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        Confirm.setText("jPasswordField2");

        Loginshell.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bin/ksh", "bin/khs", "bin/xsd", "bin/32" }));

        Homedirectory.setText("(automatic)");

        Group.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "staff", "steff", "stiff", "stoff" }));
        Group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupActionPerformed(evt);
            }
        });

        UserID.setText("(automatic)");

        Fullname.setText("user pedro");

        Username.setText("pedro");

        Nombreusuario.setText("User Name:");

        Nombrecompleto.setText("Full Name:");

        Idusuario.setText("User ID:");

        Grupo1.setText("Group:");

        Directorio.setText("Home Directory:");

        Logear.setText("Login Shell:");

        Contraseña.setText("Password:");

        Confirmarcontraseña.setText("Confirm:");

        Mensajetxt.setText("Create a new user");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botoncancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAcept)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Mensajetxt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombreusuario)
                            .addComponent(Nombrecompleto)
                            .addComponent(Idusuario)
                            .addComponent(Grupo1)
                            .addComponent(Directorio)
                            .addComponent(Logear)
                            .addComponent(Contraseña)
                            .addComponent(Confirmarcontraseña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(Confirm)
                            .addComponent(Loginshell, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Homedirectory)
                            .addComponent(UserID)
                            .addComponent(Fullname)
                            .addComponent(Username)
                            .addComponent(Group, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(Mensajetxt)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombreusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombrecompleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Idusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Group, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grupo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Homedirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Directorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Loginshell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirmarcontraseña))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAcept)
                    .addComponent(Botoncancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void GroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GroupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAcept;
    private javax.swing.JButton Botoncancel;
    private javax.swing.JPasswordField Confirm;
    private javax.swing.JLabel Confirmarcontraseña;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Directorio;
    private javax.swing.JTextField Fullname;
    private javax.swing.JComboBox<String> Group;
    private javax.swing.JLabel Grupo1;
    private javax.swing.JTextField Homedirectory;
    private javax.swing.JLabel Idusuario;
    private javax.swing.JLabel Logear;
    private javax.swing.JComboBox<String> Loginshell;
    private javax.swing.JLabel Mensajetxt;
    private javax.swing.JLabel Nombrecompleto;
    private javax.swing.JLabel Nombreusuario;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField UserID;
    private javax.swing.JTextField Username;
    // End of variables declaration//GEN-END:variables
}
